[package]
name = "bee-test"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Test utilities and feature tests for bee"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "test"]
homepage = "https://www.iota.org"

[dependencies]
rand = "0.8"
