[package]
name = "bee-node"
version = "0.1.1"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/Adam-Gleave/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "node"]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing", features = [ "auth" ] }
bee-crypto = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing" }
bee-ledger = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing", features = [ "workers" ] }
bee-message = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing" }
bee-network = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing", features = ["full"] }
bee-protocol = { path = "../bee-protocol" }
bee-rest-api = { path = "../bee-api/bee-rest-api", features = ["endpoints"] }
bee-runtime = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing" }
bee-storage = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing" }
bee-storage-rocksdb = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing" }
bee-tangle = { git = "https://github.com/Adam-Gleave/bee.git", branch = "dev-tracing" }

anymap = "0.12"
async-trait = "0.1"
cap = { version = "0.1", optional = true }
chrono = "0.4"
console-subscriber = { git = "https://github.com/tokio-rs/console.git", branch = "main" }
futures = "0.3"
fxhash = "0.2"
hex = "0.4"
iota-crypto = { version = "0.5.0", features = ["ed25519", "random", "blake2b"] }
log = "0.4"
mime_guess = { version = "2.0", optional = true }
paho-mqtt = { version = "0.9", default-features = false, features = ["bundled"]}
rand = "0.8"
rpassword = "5.0"
rust-embed = { version = "5.9", features = ["interpolate-folder-path"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = { version = "0.1", optional = true }
structopt = { version = "0.3", default-features = false }
thiserror = "1.0"
tokio = { version = "1.5", features = ["signal", "rt", "macros", "rt-multi-thread", "tracing"] }
tokio-stream = "0.1"
toml = "0.5"
tracing = "0.1.26"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.2.18", features = ["fmt", "registry", "env-filter"] }
warp = "0.3"
warp-reverse-proxy = { version = "0.3", optional = true }

[lib]
name = "bee_node"
path = "src/lib.rs"

[[bin]]
name = "bee"
path = "src/main.rs"

[features]
dashboard = [ "cap", "mime_guess", "rust-embed", "serde_repr", "warp-reverse-proxy" ]
